filebeat.prospectors:
  - type: log
    paths:
      - '/var/lib/docker/containers/*/*.log'
    json.message_key: log
    json.keys_under_root: false
    processors:
      - add_docker_metadata: ~
output.logstash:
  hosts: ["logstash:5044"]