version: '3.3'

configs:
  ls_conf:
    file: ./logstash/logstash.conf
  beats:
    file: ./filebeat/filebeat.yml

volumes:
  esdata: {}

services:
  elasticsearch:
    image: {{.Elasticsearch}}
    environment:
      - cluster.name=docker-cluster
      - network.publish_host=_eth0_
      - discovery.zen.minimum_master_nodes=3
      - discovery.zen.ping.unicast.hosts=tasks.elasticsearch
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      mode: global
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
    networks:
      - webgateway

  filebeat:
    image: {{.Filebeat}}
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    configs:
      - source: beats
        target: /usr/share/filebeat/filebeat.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    networks:
      - webgateway

  kibana:
    image: {{.Kibana}}
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_BASEPATH=/kibana
      - SERVER_NAME={{.Domain}}
      - SERVER_REWRITEBASEPATH=true
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - traefik.enable=true
        - traefik.backend=kibana
        - traefik.frontend.rule=PathPrefix:/kibana
        - traefik.port=5601
        - traefik.docker.network=webgateway
        - traefik.frontend.auth.basic.users={{.KibanaCreds}}
    networks:
      - webgateway

  logstash:
    image: {{.Logstash}}
    configs:
      - source: ls_conf
        target: /usr/share/logstash/pipeline/logstash.conf
    deploy:
      mode: replicated
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M
    environment:
      - LS_JAVA_OPTS=-Xmx1g -Xms1g
    networks:
      - webgateway

networks:
  webgateway:
    external: true
